// Mocks generated by Mockito 5.4.6 from annotations
// in picklemart/test/unit/auth/auth_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:picklemart/features/auth/data/auth_repository.dart' as _i4;
import 'package:picklemart/features/profile/data/profile_repository.dart'
    as _i6;
import 'package:picklemart/features/profile/domain/profile.dart' as _i3;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_1 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  _i5.Future<_i2.AuthResponse> signUpWithMobile({
    required String? name,
    required String? mobile,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithMobile, [], {
              #name: name,
              #mobile: mobile,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signUpWithMobile, [], {
                  #name: name,
                  #mobile: mobile,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signInWithMobile({
    required String? mobile,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithMobile, [], {
              #mobile: mobile,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signInWithMobile, [], {
                  #mobile: mobile,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signUp({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signUp, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> resetPasswordWithMobile({
    required String? mobile,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordWithMobile, [], {
              #mobile: mobile,
              #url: url,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword({
    required String? email,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email, #url: url}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> confirmRecovery({
    required String? userId,
    required String? secret,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmRecovery, [], {
              #userId: userId,
              #secret: secret,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> verifyRecoveryToken({
    required String? token,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyRecoveryToken, [], {
              #token: token,
              #email: email,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.User?> refreshUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUser, []),
            returnValue: _i5.Future<_i2.User?>.value(),
          )
          as _i5.Future<_i2.User?>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i6.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Profile?> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue: _i5.Future<_i3.Profile?>.value(),
          )
          as _i5.Future<_i3.Profile?>);

  @override
  _i5.Future<_i3.Profile?> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i5.Future<_i3.Profile?>.value(),
          )
          as _i5.Future<_i3.Profile?>);

  @override
  _i5.Future<_i3.Profile> createProfile({
    required String? userId,
    required String? name,
    String? mobile,
    String? avatarUrl,
    String? role = 'user',
    String? gender,
    DateTime? dateOfBirth,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [], {
              #userId: userId,
              #name: name,
              #mobile: mobile,
              #avatarUrl: avatarUrl,
              #role: role,
              #gender: gender,
              #dateOfBirth: dateOfBirth,
              #email: email,
            }),
            returnValue: _i5.Future<_i3.Profile>.value(
              _FakeProfile_1(
                this,
                Invocation.method(#createProfile, [], {
                  #userId: userId,
                  #name: name,
                  #mobile: mobile,
                  #avatarUrl: avatarUrl,
                  #role: role,
                  #gender: gender,
                  #dateOfBirth: dateOfBirth,
                  #email: email,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Profile>);

  @override
  _i5.Future<_i3.Profile> updateProfile({
    required String? userId,
    String? name,
    String? mobile,
    String? avatarUrl,
    bool? removeAvatar = false,
    String? gender,
    DateTime? dateOfBirth,
    String? email,
    String? gstNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #userId: userId,
              #name: name,
              #mobile: mobile,
              #avatarUrl: avatarUrl,
              #removeAvatar: removeAvatar,
              #gender: gender,
              #dateOfBirth: dateOfBirth,
              #email: email,
              #gstNumber: gstNumber,
            }),
            returnValue: _i5.Future<_i3.Profile>.value(
              _FakeProfile_1(
                this,
                Invocation.method(#updateProfile, [], {
                  #userId: userId,
                  #name: name,
                  #mobile: mobile,
                  #avatarUrl: avatarUrl,
                  #removeAvatar: removeAvatar,
                  #gender: gender,
                  #dateOfBirth: dateOfBirth,
                  #email: email,
                  #gstNumber: gstNumber,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Profile>);

  @override
  _i5.Future<void> deleteProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getProfileGst(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileGst, [userId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> profileExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#profileExists, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Profile?> getProfileByMobile(String? mobile) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileByMobile, [mobile]),
            returnValue: _i5.Future<_i3.Profile?>.value(),
          )
          as _i5.Future<_i3.Profile?>);

  @override
  _i5.Stream<_i3.Profile?> subscribeToProfileChanges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToProfileChanges, [userId]),
            returnValue: _i5.Stream<_i3.Profile?>.empty(),
          )
          as _i5.Stream<_i3.Profile?>);

  @override
  _i5.Future<_i3.Profile> updateUserRole({
    required String? userId,
    required String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [], {
              #userId: userId,
              #role: role,
            }),
            returnValue: _i5.Future<_i3.Profile>.value(
              _FakeProfile_1(
                this,
                Invocation.method(#updateUserRole, [], {
                  #userId: userId,
                  #role: role,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Profile>);

  @override
  _i5.Future<List<_i3.Profile>> getAllProfiles({
    int? limit,
    int? offset,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllProfiles, [], {
              #limit: limit,
              #offset: offset,
              #search: search,
            }),
            returnValue: _i5.Future<List<_i3.Profile>>.value(<_i3.Profile>[]),
          )
          as _i5.Future<List<_i3.Profile>>);

  @override
  _i5.Future<int> getProfilesCount({String? search}) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesCount, [], {#search: search}),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<String> uploadProfileAvatar(
    _i7.XFile? imageFile,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileAvatar, [imageFile, userId]),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileAvatar, [imageFile, userId]),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#aud)),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [AuthResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthResponse extends _i1.Mock implements _i2.AuthResponse {
  MockAuthResponse() {
    _i1.throwOnMissingStub(this);
  }
}
