-- Create User Sessions and Locations Tables
-- Run this in Supabase SQL Editor

-- Step 1: Create user_sessions table
CREATE TABLE IF NOT EXISTS PUBLIC.USER_SESSIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID NOT NULL REFERENCES PUBLIC.PROFILES(ID) ON DELETE CASCADE,
    SESSION_ID TEXT NOT NULL UNIQUE,
    DEVICE_INFO JSONB DEFAULT '{}'::JSONB,
    IP_ADDRESS TEXT,
    LOCATION_LATITUDE DECIMAL(10, 8),
    LOCATION_LONGITUDE DECIMAL(11, 8),
    LOCATION_ADDRESS TEXT,
    STARTED_AT TIMESTAMPTZ DEFAULT NOW(),
    LAST_ACTIVITY_AT TIMESTAMPTZ DEFAULT NOW(),
    ENDED_AT TIMESTAMPTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- Step 2: Create user_locations table
CREATE TABLE IF NOT EXISTS PUBLIC.USER_LOCATIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID NOT NULL REFERENCES PUBLIC.PROFILES(ID) ON DELETE CASCADE,
    SESSION_ID TEXT,
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(11, 8) NOT NULL,
    ADDRESS TEXT,
    ACCURACY DOUBLE PRECISION,
    CAPTURED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Step 3: Create indexes for user_sessions table
CREATE INDEX IF NOT EXISTS IDX_USER_SESSIONS_USER_ID ON PUBLIC.USER_SESSIONS(USER_ID);

CREATE INDEX IF NOT EXISTS IDX_USER_SESSIONS_SESSION_ID ON PUBLIC.USER_SESSIONS(SESSION_ID);

CREATE INDEX IF NOT EXISTS IDX_USER_SESSIONS_STARTED_AT ON PUBLIC.USER_SESSIONS(STARTED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_USER_SESSIONS_IS_ACTIVE ON PUBLIC.USER_SESSIONS(IS_ACTIVE);

CREATE INDEX IF NOT EXISTS IDX_USER_SESSIONS_LAST_ACTIVITY ON PUBLIC.USER_SESSIONS(LAST_ACTIVITY_AT DESC);

-- Step 4: Create indexes for user_locations table
CREATE INDEX IF NOT EXISTS IDX_USER_LOCATIONS_USER_ID ON PUBLIC.USER_LOCATIONS(USER_ID);

CREATE INDEX IF NOT EXISTS IDX_USER_LOCATIONS_SESSION_ID ON PUBLIC.USER_LOCATIONS(SESSION_ID);

CREATE INDEX IF NOT EXISTS IDX_USER_LOCATIONS_CAPTURED_AT ON PUBLIC.USER_LOCATIONS(CAPTURED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_USER_LOCATIONS_USER_CAPTURED ON PUBLIC.USER_LOCATIONS(USER_ID, CAPTURED_AT DESC);

-- Step 5: Enable Row Level Security (RLS)
ALTER TABLE PUBLIC.USER_SESSIONS ENABLE ROW LEVEL SECURITY;

ALTER TABLE PUBLIC.USER_LOCATIONS ENABLE ROW LEVEL SECURITY;

-- Step 6: Create RLS policies for user_sessions table
-- Users can INSERT their own sessions
DROP POLICY IF EXISTS "Users can insert their own sessions" ON PUBLIC.USER_SESSIONS;

CREATE POLICY "Users can insert their own sessions" ON PUBLIC.USER_SESSIONS
    FOR INSERT
    TO AUTHENTICATED
    WITH CHECK (AUTH.UID() = USER_ID);

-- Users can SELECT their own sessions
DROP POLICY IF EXISTS "Users can select their own sessions" ON PUBLIC.USER_SESSIONS;

CREATE POLICY "Users can select their own sessions" ON PUBLIC.USER_SESSIONS
    FOR SELECT
    TO AUTHENTICATED
    USING (AUTH.UID() = USER_ID);

-- Users can UPDATE their own sessions
DROP POLICY IF EXISTS "Users can update their own sessions" ON PUBLIC.USER_SESSIONS;

CREATE POLICY "Users can update their own sessions" ON PUBLIC.USER_SESSIONS
    FOR UPDATE
    TO AUTHENTICATED
    USING (AUTH.UID() = USER_ID)
    WITH CHECK (AUTH.UID() = USER_ID);

-- Admins can SELECT all sessions
DROP POLICY IF EXISTS "Admins can select all sessions" ON PUBLIC.USER_SESSIONS;

CREATE POLICY "Admins can select all sessions" ON PUBLIC.USER_SESSIONS
    FOR SELECT
    TO AUTHENTICATED
    USING (
        EXISTS (
    SELECT
                  1
    FROM
                  PUBLIC.PROFILES
    WHERE
                  ID = AUTH.UID()
        AND ROLE IN ('admin', 'manager', 'support')
)
    );

-- Step 7: Create RLS policies for user_locations table
-- Users can INSERT their own locations
DROP POLICY IF EXISTS "Users can insert their own locations" ON PUBLIC.USER_LOCATIONS;

CREATE POLICY "Users can insert their own locations" ON PUBLIC.USER_LOCATIONS
    FOR INSERT
    TO AUTHENTICATED
    WITH CHECK (AUTH.UID() = USER_ID);

-- Users can SELECT their own locations
DROP POLICY IF EXISTS "Users can select their own locations" ON PUBLIC.USER_LOCATIONS;

CREATE POLICY "Users can select their own locations" ON PUBLIC.USER_LOCATIONS
    FOR SELECT
    TO AUTHENTICATED
    USING (AUTH.UID() = USER_ID);

-- Admins can SELECT all locations
DROP POLICY IF EXISTS "Admins can select all locations" ON PUBLIC.USER_LOCATIONS;

CREATE POLICY "Admins can select all locations" ON PUBLIC.USER_LOCATIONS
    FOR SELECT
    TO AUTHENTICATED
    USING (
        EXISTS (
    SELECT
                  1
    FROM
                  PUBLIC.PROFILES
    WHERE
                  ID = AUTH.UID()
        AND ROLE IN ('admin', 'manager', 'support')
)
    );

-- Step 8: Create function to update last_activity_at automatically
CREATE OR REPLACE FUNCTION PUBLIC.UPDATE_SESSION_ACTIVITY(
) RETURNS TRIGGER AS
    $$     BEGIN UPDATE PUBLIC.USER_SESSIONS SET LAST_ACTIVITY_AT = NOW() WHERE SESSION_ID = NEW.SESSION_ID AND IS_ACTIVE = TRUE;
    RETURN NEW;
END;
$$     LANGUAGE PLPGSQL;
 
-- Step 9: Create trigger to update session activity when location is captured
DROP   TRIGGER IF EXISTS TRG_UPDATE_SESSION_ON_LOCATION ON PUBLIC.USER_LOCATIONS;
CREATE TRIGGER TRG_UPDATE_SESSION_ON_LOCATION AFTER INSERT ON PUBLIC.USER_LOCATIONS FOR EACH ROW EXECUTE FUNCTION PUBLIC.UPDATE_SESSION_ACTIVITY(
);
 
-- Step 10: Verify tables were created
SELECT
    '✅ User sessions and locations tables created successfully' AS STATUS,
    (
        SELECT
            COUNT(*)
        FROM
            INFORMATION_SCHEMA.TABLES
        WHERE
            TABLE_SCHEMA = 'public'
            AND TABLE_NAME = 'user_sessions'
    ) AS USER_SESSIONS_TABLE_EXISTS,
    (
        SELECT
            COUNT(*)
        FROM
            INFORMATION_SCHEMA.TABLES
        WHERE
            TABLE_SCHEMA = 'public'
            AND TABLE_NAME = 'user_locations'
    ) AS USER_LOCATIONS_TABLE_EXISTS,
    (
        SELECT
            COUNT(*)
        FROM
            INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        WHERE
            TABLE_SCHEMA = 'public'
            AND TABLE_NAME = 'user_sessions'
            AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    ) AS SESSIONS_FOREIGN_KEYS_EXIST,
    (
        SELECT
            COUNT(*)
        FROM
            INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        WHERE
            TABLE_SCHEMA = 'public'
            AND TABLE_NAME = 'user_locations'
            AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    ) AS LOCATIONS_FOREIGN_KEYS_EXIST;