-- ============================================================================
-- Create Product Ratings Table and Update Products Table
-- ============================================================================

-- Step 1: Create product_ratings table
CREATE TABLE IF NOT EXISTS PUBLIC.PRODUCT_RATINGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PRODUCT_ID UUID NOT NULL REFERENCES PUBLIC.PRODUCTS(ID) ON DELETE CASCADE,
    USER_ID UUID NOT NULL REFERENCES PUBLIC.PROFILES(ID) ON DELETE CASCADE,
    ORDER_ID UUID REFERENCES PUBLIC.ORDERS(ID) ON DELETE SET NULL,
    RATING INTEGER NOT NULL CHECK (RATING >= 1 AND RATING <= 5),
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(PRODUCT_ID, USER_ID)
);

-- Step 2: Create indexes for product_ratings table
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_RATINGS_PRODUCT_ID ON PUBLIC.PRODUCT_RATINGS(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_RATINGS_USER_ID ON PUBLIC.PRODUCT_RATINGS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_RATINGS_RATING ON PUBLIC.PRODUCT_RATINGS(RATING);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_RATINGS_ORDER_ID ON PUBLIC.PRODUCT_RATINGS(ORDER_ID);

-- Step 3: Add rating columns to products table
ALTER TABLE PUBLIC.PRODUCTS 
ADD COLUMN IF NOT EXISTS AVERAGE_RATING DECIMAL(3,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS RATING_COUNT INTEGER DEFAULT 0;

-- Step 4: Create indexes for rating filtering on products table
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_AVERAGE_RATING ON PUBLIC.PRODUCTS(AVERAGE_RATING);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_RATING_COUNT ON PUBLIC.PRODUCTS(RATING_COUNT);

-- Step 5: Create function to calculate and update product average rating
CREATE OR REPLACE FUNCTION PUBLIC.UPDATE_PRODUCT_RATING()
RETURNS TRIGGER AS $$
BEGIN
    -- Calculate new average rating and count
    UPDATE PUBLIC.PRODUCTS
    SET 
        AVERAGE_RATING = (
            SELECT COALESCE(ROUND(AVG(RATING)::NUMERIC, 2), 0.00)
            FROM PUBLIC.PRODUCT_RATINGS
            WHERE PRODUCT_ID = COALESCE(NEW.PRODUCT_ID, OLD.PRODUCT_ID)
        ),
        RATING_COUNT = (
            SELECT COUNT(*)
            FROM PUBLIC.PRODUCT_RATINGS
            WHERE PRODUCT_ID = COALESCE(NEW.PRODUCT_ID, OLD.PRODUCT_ID)
        ),
        UPDATED_AT = NOW()
    WHERE ID = COALESCE(NEW.PRODUCT_ID, OLD.PRODUCT_ID);
    
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE PLPGSQL;

-- Step 6: Create triggers to update product ratings on insert/update/delete
DROP TRIGGER IF EXISTS TRG_UPDATE_PRODUCT_RATING_INSERT ON PUBLIC.PRODUCT_RATINGS;
CREATE TRIGGER TRG_UPDATE_PRODUCT_RATING_INSERT
    AFTER INSERT ON PUBLIC.PRODUCT_RATINGS
    FOR EACH ROW
    EXECUTE FUNCTION PUBLIC.UPDATE_PRODUCT_RATING();

DROP TRIGGER IF EXISTS TRG_UPDATE_PRODUCT_RATING_UPDATE ON PUBLIC.PRODUCT_RATINGS;
CREATE TRIGGER TRG_UPDATE_PRODUCT_RATING_UPDATE
    AFTER UPDATE ON PUBLIC.PRODUCT_RATINGS
    FOR EACH ROW
    EXECUTE FUNCTION PUBLIC.UPDATE_PRODUCT_RATING();

DROP TRIGGER IF EXISTS TRG_UPDATE_PRODUCT_RATING_DELETE ON PUBLIC.PRODUCT_RATINGS;
CREATE TRIGGER TRG_UPDATE_PRODUCT_RATING_DELETE
    AFTER DELETE ON PUBLIC.PRODUCT_RATINGS
    FOR EACH ROW
    EXECUTE FUNCTION PUBLIC.UPDATE_PRODUCT_RATING();

-- Step 7: Create trigger to update updated_at on product_ratings
DROP TRIGGER IF EXISTS UPDATE_PRODUCT_RATINGS_UPDATED_AT ON PUBLIC.PRODUCT_RATINGS;
CREATE TRIGGER UPDATE_PRODUCT_RATINGS_UPDATED_AT
    BEFORE UPDATE ON PUBLIC.PRODUCT_RATINGS
    FOR EACH ROW
    EXECUTE FUNCTION PUBLIC.UPDATE_UPDATED_AT_COLUMN();

-- Step 8: Enable Row Level Security
ALTER TABLE PUBLIC.PRODUCT_RATINGS ENABLE ROW LEVEL SECURITY;

-- Step 9: Drop existing policies if they exist
DROP POLICY IF EXISTS product_ratings_select_all ON PUBLIC.PRODUCT_RATINGS;
DROP POLICY IF EXISTS product_ratings_insert_own ON PUBLIC.PRODUCT_RATINGS;
DROP POLICY IF EXISTS product_ratings_update_own ON PUBLIC.PRODUCT_RATINGS;
DROP POLICY IF EXISTS product_ratings_delete_own ON PUBLIC.PRODUCT_RATINGS;
DROP POLICY IF EXISTS product_ratings_admin_all ON PUBLIC.PRODUCT_RATINGS;

-- Step 10: RLS Policy: Users can SELECT all ratings (for viewing)
CREATE POLICY product_ratings_select_all ON PUBLIC.PRODUCT_RATINGS
    FOR SELECT
    USING (TRUE);

-- Step 11: RLS Policy: Users can INSERT their own ratings
CREATE POLICY product_ratings_insert_own ON PUBLIC.PRODUCT_RATINGS
    FOR INSERT
    WITH CHECK (AUTH.UID() = USER_ID);

-- Step 12: RLS Policy: Users can UPDATE their own ratings
CREATE POLICY product_ratings_update_own ON PUBLIC.PRODUCT_RATINGS
    FOR UPDATE
    USING (AUTH.UID() = USER_ID)
    WITH CHECK (AUTH.UID() = USER_ID);

-- Step 13: RLS Policy: Users can DELETE their own ratings
CREATE POLICY product_ratings_delete_own ON PUBLIC.PRODUCT_RATINGS
    FOR DELETE
    USING (AUTH.UID() = USER_ID);

-- Step 14: RLS Policy: Admins can SELECT/UPDATE/DELETE all ratings
CREATE POLICY product_ratings_admin_all ON PUBLIC.PRODUCT_RATINGS
    FOR ALL
    USING (PUBLIC.IS_ADMIN(AUTH.UID()))
    WITH CHECK (PUBLIC.IS_ADMIN(AUTH.UID()));

-- Step 15: Grant permissions
GRANT ALL ON PUBLIC.PRODUCT_RATINGS TO AUTHENTICATED;

-- Step 16: Add star_ratings_enabled to admin_features (if table exists)
-- This will be handled by the application layer, but we can add a default entry
-- Note: The admin_features table uses feature_key and feature_value structure
-- The application will handle inserting this feature if it doesn't exist

