-- Create chat_typing_status table for typing indicators
-- Run this in Supabase SQL Editor

-- Step 1: Create chat_typing_status table
CREATE TABLE IF NOT EXISTS PUBLIC.CHAT_TYPING_STATUS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CONVERSATION_ID UUID NOT NULL REFERENCES PUBLIC.CHAT_CONVERSATIONS(ID) ON DELETE CASCADE,
    USER_ID UUID NOT NULL REFERENCES PUBLIC.PROFILES(ID) ON DELETE CASCADE,
    IS_TYPING BOOLEAN NOT NULL DEFAULT TRUE,
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(CONVERSATION_ID, USER_ID)
);

-- Step 2: Create indexes
CREATE INDEX IF NOT EXISTS IDX_CHAT_TYPING_STATUS_CONVERSATION_ID ON PUBLIC.CHAT_TYPING_STATUS(CONVERSATION_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_TYPING_STATUS_USER_ID ON PUBLIC.CHAT_TYPING_STATUS(USER_ID);

-- Step 3: Enable RLS
ALTER TABLE PUBLIC.CHAT_TYPING_STATUS ENABLE ROW LEVEL SECURITY;

-- Step 4: RLS Policies for users
DROP POLICY IF EXISTS "Users can view typing status in their conversations" ON PUBLIC.CHAT_TYPING_STATUS;
CREATE POLICY "Users can view typing status in their conversations" ON PUBLIC.CHAT_TYPING_STATUS
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1
            FROM PUBLIC.CHAT_CONVERSATIONS
            WHERE CHAT_CONVERSATIONS.ID = CHAT_TYPING_STATUS.CONVERSATION_ID
            AND CHAT_CONVERSATIONS.USER_ID = AUTH.UID()
        )
    );

DROP POLICY IF EXISTS "Users can insert typing status in their conversations" ON PUBLIC.CHAT_TYPING_STATUS;
CREATE POLICY "Users can insert typing status in their conversations" ON PUBLIC.CHAT_TYPING_STATUS
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM PUBLIC.CHAT_CONVERSATIONS
            WHERE CHAT_CONVERSATIONS.ID = CHAT_TYPING_STATUS.CONVERSATION_ID
            AND CHAT_CONVERSATIONS.USER_ID = AUTH.UID()
        )
        AND USER_ID = AUTH.UID()
    );

DROP POLICY IF EXISTS "Users can update typing status" ON PUBLIC.CHAT_TYPING_STATUS;
CREATE POLICY "Users can update typing status" ON PUBLIC.CHAT_TYPING_STATUS
    FOR UPDATE
    USING (USER_ID = AUTH.UID())
    WITH CHECK (USER_ID = AUTH.UID());

-- Step 5: Admin policies
DROP POLICY IF EXISTS "Admins can view all typing status" ON PUBLIC.CHAT_TYPING_STATUS;
CREATE POLICY "Admins can view all typing status" ON PUBLIC.CHAT_TYPING_STATUS
    FOR SELECT
    USING (PUBLIC.IS_ADMIN(AUTH.UID()));

DROP POLICY IF EXISTS "Admins can manage all typing status" ON PUBLIC.CHAT_TYPING_STATUS;
CREATE POLICY "Admins can manage all typing status" ON PUBLIC.CHAT_TYPING_STATUS
    FOR ALL
    USING (PUBLIC.IS_ADMIN(AUTH.UID()))
    WITH CHECK (PUBLIC.IS_ADMIN(AUTH.UID()));

-- Step 6: Function to auto-delete expired typing status (older than 5 seconds)
CREATE OR REPLACE FUNCTION PUBLIC.CLEANUP_EXPIRED_TYPING_STATUS()
RETURNS void AS $$
BEGIN
    DELETE FROM PUBLIC.CHAT_TYPING_STATUS
    WHERE IS_TYPING = TRUE
    AND UPDATED_AT < NOW() - INTERVAL '5 seconds';
END;
$$ LANGUAGE PLPGSQL;

-- Step 7: Add comment to table
COMMENT ON TABLE PUBLIC.CHAT_TYPING_STATUS IS 'Tracks typing status for users in chat conversations. Auto-expires after 5 seconds.';

