-- Create Payment Receipts Table
-- This migration creates the payment_receipts table for tracking payments received for orders

-- Step 1: Create payment_receipts table
CREATE TABLE IF NOT EXISTS PUBLIC.PAYMENT_RECEIPTS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ORDER_ID UUID NOT NULL REFERENCES PUBLIC.ORDERS(ID) ON DELETE CASCADE,
    CUSTOMER_ID UUID NOT NULL REFERENCES PUBLIC.PROFILES(ID) ON DELETE CASCADE,
    RECEIPT_NUMBER TEXT NOT NULL,
    PAYMENT_DATE TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    AMOUNT DECIMAL(10,2) NOT NULL CHECK (AMOUNT > 0),
    PAYMENT_TYPE TEXT NOT NULL DEFAULT 'cash' 
        CHECK (PAYMENT_TYPE IN ('cash', 'bank_transfer', 'cheque', 'upi', 'credit_card', 'other')),
    DESCRIPTION TEXT,
    ATTACHMENT_URL TEXT,
    CREATED_BY UUID NOT NULL REFERENCES PUBLIC.PROFILES(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Step 2: Create indexes for optimization
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_RECEIPTS_ORDER_ID ON PUBLIC.PAYMENT_RECEIPTS(ORDER_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_RECEIPTS_CUSTOMER_ID ON PUBLIC.PAYMENT_RECEIPTS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_RECEIPTS_PAYMENT_DATE ON PUBLIC.PAYMENT_RECEIPTS(PAYMENT_DATE DESC);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_RECEIPTS_CREATED_BY ON PUBLIC.PAYMENT_RECEIPTS(CREATED_BY);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_RECEIPTS_RECEIPT_NUMBER ON PUBLIC.PAYMENT_RECEIPTS(RECEIPT_NUMBER);

-- Composite index for order payments
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_RECEIPTS_ORDER_DATE ON PUBLIC.PAYMENT_RECEIPTS(ORDER_ID, PAYMENT_DATE DESC);

-- Step 3: Create updated_at trigger
DROP TRIGGER IF EXISTS SET_UPDATED_AT_PAYMENT_RECEIPTS ON PUBLIC.PAYMENT_RECEIPTS;
CREATE TRIGGER SET_UPDATED_AT_PAYMENT_RECEIPTS 
    BEFORE UPDATE ON PUBLIC.PAYMENT_RECEIPTS 
    FOR EACH ROW 
    EXECUTE FUNCTION PUBLIC.HANDLE_UPDATED_AT();

-- Step 4: Enable Row Level Security (RLS)
ALTER TABLE PUBLIC.PAYMENT_RECEIPTS ENABLE ROW LEVEL SECURITY;

-- Step 5: Create RLS policies
-- Admins can do everything
CREATE POLICY "Admins can manage all payment receipts"
    ON PUBLIC.PAYMENT_RECEIPTS
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM PUBLIC.PROFILES
            WHERE PROFILES.ID = AUTH.UID()
            AND PROFILES.ROLE = 'admin'
        )
    );

-- Users can view their own payment receipts
CREATE POLICY "Users can view their own payment receipts"
    ON PUBLIC.PAYMENT_RECEIPTS
    FOR SELECT
    USING (CUSTOMER_ID = AUTH.UID());

