-- Fix Purchase Orders Schema
-- Run this in Supabase SQL Editor to fix missing tables and columns

-- 1. Ensure purchase_orders table exists
CREATE TABLE IF NOT EXISTS PUBLIC.PURCHASE_ORDERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PURCHASE_NUMBER TEXT NOT NULL UNIQUE,
    ORDER_ID UUID REFERENCES PUBLIC.ORDERS(ID) ON DELETE SET NULL,
    MANUFACTURER_ID UUID REFERENCES PUBLIC.MANUFACTURERS(ID) ON DELETE RESTRICT,
    CUSTOMER_ID UUID REFERENCES PUBLIC.PROFILES(ID) ON DELETE SET NULL,
    STATUS TEXT NOT NULL DEFAULT 'pending' 
        CHECK (STATUS IN ('pending', 'confirmed', 'received', 'cancelled')),
    SUBTOTAL DECIMAL(10, 2) NOT NULL DEFAULT 0,
    TAX DECIMAL(10, 2) NOT NULL DEFAULT 0,
    SHIPPING DECIMAL(10, 2) NOT NULL DEFAULT 0,
    TOTAL DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PURCHASE_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    EXPECTED_DELIVERY_DATE DATE,
    DELIVERY_LOCATION TEXT,
    TRANSPORTATION_NAME TEXT,
    TRANSPORTATION_PHONE TEXT,
    NOTES TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT CHECK_CUSTOMER_OR_MANUFACTURER CHECK (
        (CUSTOMER_ID IS NOT NULL AND MANUFACTURER_ID IS NULL) OR
        (CUSTOMER_ID IS NULL AND MANUFACTURER_ID IS NOT NULL)
    )
);

-- 2. Ensure purchase_order_items table exists
CREATE TABLE IF NOT EXISTS PUBLIC.PURCHASE_ORDER_ITEMS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PURCHASE_ORDER_ID UUID NOT NULL REFERENCES PUBLIC.PURCHASE_ORDERS(ID) ON DELETE CASCADE,
    PRODUCT_ID UUID NOT NULL REFERENCES PUBLIC.PRODUCTS(ID) ON DELETE RESTRICT,
    VARIANT_ID UUID REFERENCES PUBLIC.PRODUCT_VARIANTS(ID) ON DELETE SET NULL,
    MEASUREMENT_UNIT TEXT,
    NAME TEXT NOT NULL,
    CATEGORY TEXT,
    IMAGE TEXT NOT NULL,
    QUANTITY INTEGER NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    TOTAL_PRICE DECIMAL(10, 2) NOT NULL,
    NOTES TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Add columns if they are missing (for existing tables)
DO $$
BEGIN
    -- Add CUSTOMER_ID to PURCHASE_ORDERS if not exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'purchase_orders' AND column_name = 'customer_id') THEN
        ALTER TABLE PUBLIC.PURCHASE_ORDERS ADD COLUMN CUSTOMER_ID UUID REFERENCES PUBLIC.PROFILES(ID) ON DELETE SET NULL;
    END IF;

    -- Make MANUFACTURER_ID nullable if it's not
    ALTER TABLE PUBLIC.PURCHASE_ORDERS ALTER COLUMN MANUFACTURER_ID DROP NOT NULL;

    -- Add CATEGORY to PURCHASE_ORDER_ITEMS if not exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'purchase_order_items' AND column_name = 'category') THEN
        ALTER TABLE PUBLIC.PURCHASE_ORDER_ITEMS ADD COLUMN CATEGORY TEXT;
    END IF;

    -- Add manufacturer/transportation details to PURCHASE_ORDERS if not exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'purchase_orders' AND column_name = 'delivery_location') THEN
        ALTER TABLE PUBLIC.PURCHASE_ORDERS ADD COLUMN DELIVERY_LOCATION TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'purchase_orders' AND column_name = 'transportation_name') THEN
        ALTER TABLE PUBLIC.PURCHASE_ORDERS ADD COLUMN TRANSPORTATION_NAME TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'purchase_orders' AND column_name = 'transportation_phone') THEN
        ALTER TABLE PUBLIC.PURCHASE_ORDERS ADD COLUMN TRANSPORTATION_PHONE TEXT;
    END IF;
END $$;

-- 4. Enable RLS
ALTER TABLE PUBLIC.PURCHASE_ORDERS ENABLE ROW LEVEL SECURITY;
ALTER TABLE PUBLIC.PURCHASE_ORDER_ITEMS ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies (Drop existing to avoid conflicts)
DROP POLICY IF EXISTS "Admins can view all purchase orders" ON PUBLIC.PURCHASE_ORDERS;
CREATE POLICY "Admins can view all purchase orders" ON PUBLIC.PURCHASE_ORDERS FOR SELECT TO AUTHENTICATED USING (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

DROP POLICY IF EXISTS "Admins can insert purchase orders" ON PUBLIC.PURCHASE_ORDERS;
CREATE POLICY "Admins can insert purchase orders" ON PUBLIC.PURCHASE_ORDERS FOR INSERT TO AUTHENTICATED WITH CHECK (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

DROP POLICY IF EXISTS "Admins can update purchase orders" ON PUBLIC.PURCHASE_ORDERS;
CREATE POLICY "Admins can update purchase orders" ON PUBLIC.PURCHASE_ORDERS FOR UPDATE TO AUTHENTICATED USING (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
) WITH CHECK (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

DROP POLICY IF EXISTS "Admins can delete purchase orders" ON PUBLIC.PURCHASE_ORDERS;
CREATE POLICY "Admins can delete purchase orders" ON PUBLIC.PURCHASE_ORDERS FOR DELETE TO AUTHENTICATED USING (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

DROP POLICY IF EXISTS "Admins can view all purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS;
CREATE POLICY "Admins can view all purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS FOR SELECT TO AUTHENTICATED USING (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

DROP POLICY IF EXISTS "Admins can insert purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS;
CREATE POLICY "Admins can insert purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS FOR INSERT TO AUTHENTICATED WITH CHECK (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

DROP POLICY IF EXISTS "Admins can update purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS;
CREATE POLICY "Admins can update purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS FOR UPDATE TO AUTHENTICATED USING (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
) WITH CHECK (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

DROP POLICY IF EXISTS "Admins can delete purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS;
CREATE POLICY "Admins can delete purchase order items" ON PUBLIC.PURCHASE_ORDER_ITEMS FOR DELETE TO AUTHENTICATED USING (
    EXISTS (SELECT 1 FROM PUBLIC.PROFILES WHERE ID = AUTH.UID() AND ROLE IN ('admin', 'manager', 'support'))
);

-- 6. Create Indexes
CREATE INDEX IF NOT EXISTS IDX_PURCHASE_ORDERS_PURCHASE_NUMBER ON PUBLIC.PURCHASE_ORDERS(PURCHASE_NUMBER);
CREATE INDEX IF NOT EXISTS IDX_PURCHASE_ORDERS_CREATED_AT ON PUBLIC.PURCHASE_ORDERS(CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_PURCHASE_ORDER_ITEMS_PURCHASE_ORDER_ID ON PUBLIC.PURCHASE_ORDER_ITEMS(PURCHASE_ORDER_ID);

-- 7. Triggers for Updated At
CREATE OR REPLACE FUNCTION PUBLIC.HANDLE_UPDATED_AT()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = NOW();
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

DROP TRIGGER IF EXISTS SET_UPDATED_AT_PURCHASE_ORDERS ON PUBLIC.PURCHASE_ORDERS;
CREATE TRIGGER SET_UPDATED_AT_PURCHASE_ORDERS BEFORE UPDATE ON PUBLIC.PURCHASE_ORDERS FOR EACH ROW EXECUTE FUNCTION PUBLIC.HANDLE_UPDATED_AT();

DROP TRIGGER IF EXISTS SET_UPDATED_AT_PURCHASE_ORDER_ITEMS ON PUBLIC.PURCHASE_ORDER_ITEMS;
CREATE TRIGGER SET_UPDATED_AT_PURCHASE_ORDER_ITEMS BEFORE UPDATE ON PUBLIC.PURCHASE_ORDER_ITEMS FOR EACH ROW EXECUTE FUNCTION PUBLIC.HANDLE_UPDATED_AT();

-- 8. Purchase Number Generation
CREATE OR REPLACE FUNCTION PUBLIC.GENERATE_PURCHASE_NUMBER()
RETURNS TEXT AS $$
DECLARE
    next_number INTEGER;
    v_purchase_number TEXT;
BEGIN
    SELECT COALESCE(MAX(CAST(SUBSTRING(PURCHASE_NUMBER FROM '[0-9]+') AS INTEGER)), 0) + 1
    INTO next_number
    FROM PUBLIC.PURCHASE_ORDERS
    WHERE PURCHASE_NUMBER ~ '^PO[0-9]+$';
    
    v_purchase_number := 'PO' || LPAD(next_number::TEXT, 5, '0');
    
    RETURN v_purchase_number;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION PUBLIC.SET_PURCHASE_NUMBER()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.PURCHASE_NUMBER IS NULL OR NEW.PURCHASE_NUMBER = '' THEN
        NEW.PURCHASE_NUMBER := PUBLIC.GENERATE_PURCHASE_NUMBER();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

DROP TRIGGER IF EXISTS TRIGGER_SET_PURCHASE_NUMBER ON PUBLIC.PURCHASE_ORDERS;
CREATE TRIGGER TRIGGER_SET_PURCHASE_NUMBER BEFORE INSERT ON PUBLIC.PURCHASE_ORDERS FOR EACH ROW EXECUTE FUNCTION PUBLIC.SET_PURCHASE_NUMBER();
