-- Fix cascading constraints for Manufacturers and Customers
-- This migration ensures that deleting a manufacturer or customer also deletes their related records

-- 1. Fix PURCHASE_ORDERS MANUFACTURER_ID to ON DELETE CASCADE
ALTER TABLE PUBLIC.PURCHASE_ORDERS 
DROP CONSTRAINT IF EXISTS PURCHASE_ORDERS_MANUFACTURER_ID_FKEY;

-- Note: The constraint name might be different depending on when it was created.
-- We'll try the most likely name and then use a generic approach if needed.
-- In migration 049/055 it was created without an explicit name, so it defaults to purchase_orders_manufacturer_id_fkey.

ALTER TABLE PUBLIC.PURCHASE_ORDERS 
ADD CONSTRAINT PURCHASE_ORDERS_MANUFACTURER_ID_FKEY 
FOREIGN KEY (MANUFACTURER_ID) 
REFERENCES PUBLIC.MANUFACTURERS(ID) 
ON DELETE CASCADE;

-- 2. Ensure PURCHASE_ORDERS CUSTOMER_ID is ON DELETE CASCADE (Double check from 061)
ALTER TABLE PUBLIC.PURCHASE_ORDERS 
DROP CONSTRAINT IF EXISTS PURCHASE_ORDERS_CUSTOMER_ID_FKEY;

ALTER TABLE PUBLIC.PURCHASE_ORDERS 
ADD CONSTRAINT PURCHASE_ORDERS_CUSTOMER_ID_FKEY 
FOREIGN KEY (CUSTOMER_ID) 
REFERENCES PUBLIC.PROFILES(ID) 
ON DELETE CASCADE;

-- 3. Ensure CREDIT_TRANSACTIONS MANUFACTURER_ID is ON DELETE CASCADE
-- This was already set in 039 but let's be explicit to ensure consistency
ALTER TABLE PUBLIC.CREDIT_TRANSACTIONS 
DROP CONSTRAINT IF EXISTS CREDIT_TRANSACTIONS_MANUFACTURER_ID_FKEY;

ALTER TABLE PUBLIC.CREDIT_TRANSACTIONS 
ADD CONSTRAINT CREDIT_TRANSACTIONS_MANUFACTURER_ID_FKEY 
FOREIGN KEY (MANUFACTURER_ID) 
REFERENCES PUBLIC.MANUFACTURERS(ID) 
ON DELETE CASCADE;

-- 4. Ensure PAYMENT_RECEIPTS CUSTOMER_ID is ON DELETE CASCADE
ALTER TABLE PUBLIC.PAYMENT_RECEIPTS 
DROP CONSTRAINT IF EXISTS PAYMENT_RECEIPTS_CUSTOMER_ID_FKEY;

ALTER TABLE PUBLIC.PAYMENT_RECEIPTS 
ADD CONSTRAINT PAYMENT_RECEIPTS_CUSTOMER_ID_FKEY 
FOREIGN KEY (CUSTOMER_ID) 
REFERENCES PUBLIC.PROFILES(ID) 
ON DELETE CASCADE;

-- Add comments for clarity
COMMENT ON CONSTRAINT PURCHASE_ORDERS_MANUFACTURER_ID_FKEY ON PUBLIC.PURCHASE_ORDERS IS 'Cascading delete for manufacturers in purchase orders';
COMMENT ON CONSTRAINT PURCHASE_ORDERS_CUSTOMER_ID_FKEY ON PUBLIC.PURCHASE_ORDERS IS 'Cascading delete for customers in purchase orders';
COMMENT ON CONSTRAINT CREDIT_TRANSACTIONS_MANUFACTURER_ID_FKEY ON PUBLIC.CREDIT_TRANSACTIONS IS 'Cascading delete for manufacturers in credit transactions';
COMMENT ON CONSTRAINT PAYMENT_RECEIPTS_CUSTOMER_ID_FKEY ON PUBLIC.PAYMENT_RECEIPTS IS 'Cascading delete for customers in payment receipts';
