import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:latlong2/latlong.dart';
import '../data/address_repository.dart';
import '../data/address_repository_provider.dart';
import '../../auth/application/auth_controller.dart';

/// Address state
class AddressState {
  final List<Address> addresses;
  final bool isLoading;
  final String? error;
  final Address? selectedAddress;

  const AddressState({
    this.addresses = const [],
    this.isLoading = false,
    this.error,
    this.selectedAddress,
  });

  AddressState copyWith({
    List<Address>? addresses,
    bool? isLoading,
    String? error,
    Address? selectedAddress,
  }) {
    return AddressState(
      addresses: addresses ?? this.addresses,
      isLoading: isLoading ?? this.isLoading,
      error: error,
      selectedAddress: selectedAddress ?? this.selectedAddress,
    );
  }
}

/// Address controller with real-time updates
class AddressController extends StateNotifier<AddressState> {
  final AddressRepository _repository;
  final Ref _ref;
  StreamSubscription<List<Address>>? _addressSubscription;
  String? _currentUserId;

  AddressController(this._repository, this._ref) : super(const AddressState()) {
    _initialize();
  }

  /// Initialize address controller
  Future<void> _initialize() async {
    // Listen to auth state changes
    _ref.listen<AuthState>(authControllerProvider, (previous, next) {
      if (previous?.isAuthenticated != next.isAuthenticated) {
        if (next.isAuthenticated && next.userId != null) {
          // User logged in: load addresses and subscribe to real-time changes
          _currentUserId = next.userId;
          _loadAddresses(next.userId!);
          _subscribeToAddressChanges(next.userId!);
        } else {
          // User logged out: clear addresses and cancel subscription
          _currentUserId = null;
          _addressSubscription?.cancel();
          _addressSubscription = null;
          state = const AddressState();
        }
      } else if (next.isAuthenticated && 
                 next.userId != null && 
                 next.userId != _currentUserId) {
        // User ID changed: reload addresses
        _currentUserId = next.userId;
        _loadAddresses(next.userId!);
        _subscribeToAddressChanges(next.userId!);
      }
    });

    // Load addresses if user is already authenticated
    final authState = _ref.read(authControllerProvider);
    if (authState.isAuthenticated && authState.userId != null) {
      _currentUserId = authState.userId;
      await _loadAddresses(authState.userId!);
      _subscribeToAddressChanges(authState.userId!);
    }
  }

  /// Load addresses from server
  Future<void> _loadAddresses(String userId) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      final addresses = await _repository.fetchAddresses(userId);
      state = state.copyWith(addresses: addresses, isLoading: false);
    } catch (e) {
      if (kDebugMode) {
        print('Error loading addresses: $e');
      }
      state = state.copyWith(
        isLoading: false,
        error: 'Failed to load addresses: ${e.toString()}',
      );
    }
  }

  /// Subscribe to real-time address changes
  void _subscribeToAddressChanges(String userId) {
    // Cancel existing subscription
    _addressSubscription?.cancel();

    // Subscribe to real-time changes
    _addressSubscription = _repository.subscribeToAddressChanges(userId).listen(
      (addresses) {
        state = state.copyWith(addresses: addresses, error: null);
      },
      onError: (error) {
        if (kDebugMode) {
          print('Error in address subscription: $error');
        }
        // Don't update state on subscription error, just log it
      },
    );
  }

  /// Refresh addresses manually
  Future<void> refresh() async {
    if (_currentUserId != null) {
      await _loadAddresses(_currentUserId!);
    }
  }

  /// Create a new address
  Future<Address?> createAddress({
    required String name,
    required String phone,
    required String address,
    required String city,
    required String stateValue,
    required String pincode,
    LatLng? coordinates,
    String? notes,
    bool isDefault = false,
  }) async {
    if (_currentUserId == null) {
      state = state.copyWith(error: 'User not authenticated');
      return null;
    }

    // Check if user already has an address
    if (state.addresses.isNotEmpty) {
      state = state.copyWith(
        error: 'You can only have one address. Please edit your existing address.',
      );
      return null;
    }

    state = state.copyWith(isLoading: true, error: null);
    try {
      final newAddress = Address(
        id: '', // Will be generated by database
        name: name,
        phone: phone,
        address: address,
        city: city,
        state: stateValue,
        pincode: pincode,
        coordinates: coordinates,
        notes: notes,
        isDefault: isDefault,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final createdAddress = await _repository.createAddress(
        newAddress,
        _currentUserId!,
      );

      // Real-time subscription will update the state automatically
      state = state.copyWith(isLoading: false);
      return createdAddress;
    } catch (e) {
      if (kDebugMode) {
        print('Error creating address: $e');
      }
      
      // Check if error is due to unique constraint violation
      final errorMessage = e.toString().toLowerCase();
      if (errorMessage.contains('unique') || errorMessage.contains('duplicate')) {
        state = state.copyWith(
          isLoading: false,
          error: 'You can only have one address. Please edit your existing address.',
        );
      } else {
        state = state.copyWith(
          isLoading: false,
          error: 'Failed to create address: ${e.toString()}',
        );
      }
      return null;
    }
  }

  /// Update an existing address
  Future<Address?> updateAddress(Address address) async {
    if (_currentUserId == null) {
      state = state.copyWith(error: 'User not authenticated');
      return null;
    }

    state = state.copyWith(isLoading: true, error: null);
    try {
      final updatedAddress = await _repository.updateAddress(
        address,
        _currentUserId!,
      );

      // Real-time subscription will update the state automatically
      state = state.copyWith(isLoading: false);
      return updatedAddress;
    } catch (e) {
      if (kDebugMode) {
        print('Error updating address: $e');
      }
      state = state.copyWith(
        isLoading: false,
        error: 'Failed to update address: ${e.toString()}',
      );
      return null;
    }
  }

  /// Delete an address
  Future<bool> deleteAddress(String addressId) async {
    if (_currentUserId == null) {
      state = state.copyWith(error: 'User not authenticated');
      return false;
    }

    // Optimistic update: immediately remove the address from the list
    final addressToDelete = state.addresses.firstWhere(
      (addr) => addr.id == addressId,
      orElse: () => throw Exception('Address not found'),
    );
    
    final updatedAddresses = state.addresses
        .where((addr) => addr.id != addressId)
        .toList();
    
    state = state.copyWith(
      addresses: updatedAddresses,
      isLoading: true,
      error: null,
    );

    try {
      await _repository.deleteAddress(addressId, _currentUserId!);
      
      // Deletion succeeded - state already updated optimistically
      // Real-time subscription or refresh will ensure final consistency
      state = state.copyWith(isLoading: false);
      return true;
    } catch (e) {
      if (kDebugMode) {
        print('Error deleting address: $e');
      }
      
      // Deletion failed - restore the address by reloading from server
      await _loadAddresses(_currentUserId!);
      
      state = state.copyWith(
        isLoading: false,
        error: 'Failed to delete address: ${e.toString()}',
      );
      return false;
    }
  }

  /// Select an address
  void selectAddress(Address? address) {
    state = state.copyWith(selectedAddress: address);
  }

  /// Get default address
  Address? get defaultAddress {
    try {
      return state.addresses.firstWhere(
        (address) => address.isDefault,
      );
    } catch (e) {
      return null;
    }
  }

  /// Clear error
  void clearError() {
    state = state.copyWith(error: null);
  }

  @override
  void dispose() {
    _addressSubscription?.cancel();
    super.dispose();
  }
}

/// Address controller provider
final addressControllerProvider =
    StateNotifierProvider<AddressController, AddressState>((ref) {
  final repository = ref.watch(addressRepositoryProvider);
  return AddressController(repository, ref);
});

