// Mocks generated by Mockito 5.4.6 from annotations
// in picklemart/test/unit/profile/profile_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:picklemart/features/profile/data/profile_repository.dart'
    as _i3;
import 'package:picklemart/features/profile/domain/profile.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfile_0 extends _i1.SmartFake implements _i2.Profile {
  _FakeProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Profile?> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue: _i4.Future<_i2.Profile?>.value(),
          )
          as _i4.Future<_i2.Profile?>);

  @override
  _i4.Future<_i2.Profile?> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i4.Future<_i2.Profile?>.value(),
          )
          as _i4.Future<_i2.Profile?>);

  @override
  _i4.Future<_i2.Profile> createProfile({
    required String? userId,
    required String? name,
    String? mobile,
    String? avatarUrl,
    String? role = 'user',
    String? gender,
    DateTime? dateOfBirth,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [], {
              #userId: userId,
              #name: name,
              #mobile: mobile,
              #avatarUrl: avatarUrl,
              #role: role,
              #gender: gender,
              #dateOfBirth: dateOfBirth,
              #email: email,
            }),
            returnValue: _i4.Future<_i2.Profile>.value(
              _FakeProfile_0(
                this,
                Invocation.method(#createProfile, [], {
                  #userId: userId,
                  #name: name,
                  #mobile: mobile,
                  #avatarUrl: avatarUrl,
                  #role: role,
                  #gender: gender,
                  #dateOfBirth: dateOfBirth,
                  #email: email,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Profile>);

  @override
  _i4.Future<_i2.Profile> updateProfile({
    required String? userId,
    String? name,
    String? mobile,
    String? avatarUrl,
    bool? removeAvatar = false,
    String? gender,
    DateTime? dateOfBirth,
    String? email,
    String? gstNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #userId: userId,
              #name: name,
              #mobile: mobile,
              #avatarUrl: avatarUrl,
              #removeAvatar: removeAvatar,
              #gender: gender,
              #dateOfBirth: dateOfBirth,
              #email: email,
              #gstNumber: gstNumber,
            }),
            returnValue: _i4.Future<_i2.Profile>.value(
              _FakeProfile_0(
                this,
                Invocation.method(#updateProfile, [], {
                  #userId: userId,
                  #name: name,
                  #mobile: mobile,
                  #avatarUrl: avatarUrl,
                  #removeAvatar: removeAvatar,
                  #gender: gender,
                  #dateOfBirth: dateOfBirth,
                  #email: email,
                  #gstNumber: gstNumber,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Profile>);

  @override
  _i4.Future<void> deleteProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getProfileGst(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileGst, [userId]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> profileExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#profileExists, [userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Profile?> getProfileByMobile(String? mobile) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileByMobile, [mobile]),
            returnValue: _i4.Future<_i2.Profile?>.value(),
          )
          as _i4.Future<_i2.Profile?>);

  @override
  _i4.Stream<_i2.Profile?> subscribeToProfileChanges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToProfileChanges, [userId]),
            returnValue: _i4.Stream<_i2.Profile?>.empty(),
          )
          as _i4.Stream<_i2.Profile?>);

  @override
  _i4.Future<_i2.Profile> updateUserRole({
    required String? userId,
    required String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [], {
              #userId: userId,
              #role: role,
            }),
            returnValue: _i4.Future<_i2.Profile>.value(
              _FakeProfile_0(
                this,
                Invocation.method(#updateUserRole, [], {
                  #userId: userId,
                  #role: role,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Profile>);

  @override
  _i4.Future<List<_i2.Profile>> getAllProfiles({
    int? limit,
    int? offset,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllProfiles, [], {
              #limit: limit,
              #offset: offset,
              #search: search,
            }),
            returnValue: _i4.Future<List<_i2.Profile>>.value(<_i2.Profile>[]),
          )
          as _i4.Future<List<_i2.Profile>>);

  @override
  _i4.Future<int> getProfilesCount({String? search}) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesCount, [], {#search: search}),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<String> uploadProfileAvatar(
    _i5.XFile? imageFile,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileAvatar, [imageFile, userId]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileAvatar, [imageFile, userId]),
              ),
            ),
          )
          as _i4.Future<String>);
}
