// Mocks generated by Mockito 5.4.6 from annotations
// in picklemart/test/unit/admin/admin_order_controller_update_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:picklemart/features/admin/data/payment_receipt_repository.dart'
    as _i3;
import 'package:picklemart/features/cart/application/cart_controller.dart'
    as _i6;
import 'package:picklemart/features/orders/data/order_model.dart' as _i2;
import 'package:picklemart/features/orders/data/order_repository_supabase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrder_0 extends _i1.SmartFake implements _i2.Order {
  _FakeOrder_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentReceipt_1 extends _i1.SmartFake
    implements _i3.PaymentReceipt {
  _FakePaymentReceipt_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepositorySupabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepositorySupabase extends _i1.Mock
    implements _i4.OrderRepositorySupabase {
  MockOrderRepositorySupabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Order> createOrder({
    String? orderNumber,
    required List<_i6.CartItem>? cartItems,
    required _i2.OrderAddress? deliveryAddress,
    required double? subtotal,
    required double? shipping,
    required double? tax,
    required double? total,
    String? notes,
    String? userId,
    _i2.OrderStatus? status,
    double? oldDue = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #orderNumber: orderNumber,
              #cartItems: cartItems,
              #deliveryAddress: deliveryAddress,
              #subtotal: subtotal,
              #shipping: shipping,
              #tax: tax,
              #total: total,
              #notes: notes,
              #userId: userId,
              #status: status,
              #oldDue: oldDue,
            }),
            returnValue: _i5.Future<_i2.Order>.value(
              _FakeOrder_0(
                this,
                Invocation.method(#createOrder, [], {
                  #orderNumber: orderNumber,
                  #cartItems: cartItems,
                  #deliveryAddress: deliveryAddress,
                  #subtotal: subtotal,
                  #shipping: shipping,
                  #tax: tax,
                  #total: total,
                  #notes: notes,
                  #userId: userId,
                  #status: status,
                  #oldDue: oldDue,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Order>);

  @override
  _i5.Future<_i2.Order?> getOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [orderId]),
            returnValue: _i5.Future<_i2.Order?>.value(),
          )
          as _i5.Future<_i2.Order?>);

  @override
  _i5.Future<List<_i2.Order>> getUserOrders({int? page = 1, int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i5.Future<List<_i2.Order>>);

  @override
  _i5.Future<List<_i2.Order>> getAllOrders({
    int? page = 1,
    int? limit = 50,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllOrders, [], {
              #page: page,
              #limit: limit,
              #searchQuery: searchQuery,
            }),
            returnValue: _i5.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i5.Future<List<_i2.Order>>);

  @override
  _i5.Future<List<_i2.Order>> getOrdersByCustomer(
    String? customerId, {
    int? page = 1,
    int? limit = 50,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getOrdersByCustomer,
              [customerId],
              {#page: page, #limit: limit, #searchQuery: searchQuery},
            ),
            returnValue: _i5.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i5.Future<List<_i2.Order>>);

  @override
  _i5.Future<_i2.Order?> updateOrderStatus(
    String? orderId,
    _i2.OrderStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [orderId, status]),
            returnValue: _i5.Future<_i2.Order?>.value(),
          )
          as _i5.Future<_i2.Order?>);

  @override
  _i5.Future<_i2.Order?> updateOrderTracking(
    String? orderId,
    String? trackingNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderTracking, [orderId, trackingNumber]),
            returnValue: _i5.Future<_i2.Order?>.value(),
          )
          as _i5.Future<_i2.Order?>);

  @override
  _i5.Future<_i2.Order?> updateOrderDeliveryAddress(
    String? orderId,
    _i2.OrderAddress? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderDeliveryAddress, [orderId, address]),
            returnValue: _i5.Future<_i2.Order?>.value(),
          )
          as _i5.Future<_i2.Order?>);

  @override
  _i5.Future<_i2.Order?> updateOrderDetails({
    required String? orderId,
    required _i2.OrderAddress? deliveryAddress,
    required double? shipping,
    double? oldDue = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderDetails, [], {
              #orderId: orderId,
              #deliveryAddress: deliveryAddress,
              #shipping: shipping,
              #oldDue: oldDue,
            }),
            returnValue: _i5.Future<_i2.Order?>.value(),
          )
          as _i5.Future<_i2.Order?>);

  @override
  _i5.Future<Map<String, dynamic>> getOrderMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getOrderMetrics, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Stream<List<_i2.Order>> watchUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserOrders, [userId]),
            returnValue: _i5.Stream<List<_i2.Order>>.empty(),
          )
          as _i5.Stream<List<_i2.Order>>);

  @override
  _i5.Stream<List<_i2.Order>> subscribeToAllOrders() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToAllOrders, []),
            returnValue: _i5.Stream<List<_i2.Order>>.empty(),
          )
          as _i5.Stream<List<_i2.Order>>);

  @override
  _i5.Future<Map<String, dynamic>> getOrdersDashboardMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersDashboardMetrics, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i2.Order>> getOpenOrders({
    int? page = 1,
    int? limit = 50,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOpenOrders, [], {
              #page: page,
              #limit: limit,
              #searchQuery: searchQuery,
            }),
            returnValue: _i5.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i5.Future<List<_i2.Order>>);

  @override
  _i5.Future<_i2.Order?> updateOrderItems(
    String? orderId,
    List<_i2.OrderItem>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderItems, [orderId, items]),
            returnValue: _i5.Future<_i2.Order?>.value(),
          )
          as _i5.Future<_i2.Order?>);

  @override
  _i5.Future<_i2.Order?> convertOrderToSale({
    required String? orderId,
    required double? shippingPrice,
    double? oldDue = 0.0,
    bool? roundOff = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertOrderToSale, [], {
              #orderId: orderId,
              #shippingPrice: shippingPrice,
              #oldDue: oldDue,
              #roundOff: roundOff,
            }),
            returnValue: _i5.Future<_i2.Order?>.value(),
          )
          as _i5.Future<_i2.Order?>);

  @override
  _i5.Future<bool> deleteOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [orderId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<void> subscribeToUserOrders() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToUserOrders, []),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);
}

/// A class which mocks [PaymentReceiptRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentReceiptRepository extends _i1.Mock
    implements _i3.PaymentReceiptRepository {
  MockPaymentReceiptRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<double> getTotalPaidForOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPaidForOrder, [orderId]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<List<_i3.PaymentReceipt>> getPaymentsForOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsForOrder, [orderId]),
            returnValue: _i5.Future<List<_i3.PaymentReceipt>>.value(
              <_i3.PaymentReceipt>[],
            ),
          )
          as _i5.Future<List<_i3.PaymentReceipt>>);

  @override
  _i5.Future<Map<String, double>> getTotalPaidForAllOrders({
    List<String>? orderIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPaidForAllOrders, [], {
              #orderIds: orderIds,
            }),
            returnValue: _i5.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<Map<String, double>> getTotalPaidForAllCustomers({
    List<String>? customerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPaidForAllCustomers, [], {
              #customerIds: customerIds,
            }),
            returnValue: _i5.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<_i3.PaymentReceipt>> getAllPaymentReceipts({
    int? page = 1,
    int? limit = 20,
    String? searchQuery,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPaymentReceipts, [], {
              #page: page,
              #limit: limit,
              #searchQuery: searchQuery,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<List<_i3.PaymentReceipt>>.value(
              <_i3.PaymentReceipt>[],
            ),
          )
          as _i5.Future<List<_i3.PaymentReceipt>>);

  @override
  _i5.Future<_i3.PaymentReceipt> createPaymentReceipt({
    String? orderId,
    required String? customerId,
    required String? receiptNumber,
    required DateTime? paymentDate,
    required double? amount,
    required String? paymentType,
    String? description,
    String? attachmentUrl,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPaymentReceipt, [], {
              #orderId: orderId,
              #customerId: customerId,
              #receiptNumber: receiptNumber,
              #paymentDate: paymentDate,
              #amount: amount,
              #paymentType: paymentType,
              #description: description,
              #attachmentUrl: attachmentUrl,
              #createdBy: createdBy,
            }),
            returnValue: _i5.Future<_i3.PaymentReceipt>.value(
              _FakePaymentReceipt_1(
                this,
                Invocation.method(#createPaymentReceipt, [], {
                  #orderId: orderId,
                  #customerId: customerId,
                  #receiptNumber: receiptNumber,
                  #paymentDate: paymentDate,
                  #amount: amount,
                  #paymentType: paymentType,
                  #description: description,
                  #attachmentUrl: attachmentUrl,
                  #createdBy: createdBy,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.PaymentReceipt>);

  @override
  _i5.Future<List<_i3.PaymentReceipt>> getReceiptsByCustomer(
    String? customerId, {
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getReceiptsByCustomer,
              [customerId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i5.Future<List<_i3.PaymentReceipt>>.value(
              <_i3.PaymentReceipt>[],
            ),
          )
          as _i5.Future<List<_i3.PaymentReceipt>>);

  @override
  _i5.Future<bool> updatePaymentReceipt({
    required String? id,
    double? amount,
    String? paymentType,
    String? description,
    String? customerName,
    String? customerPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePaymentReceipt, [], {
              #id: id,
              #amount: amount,
              #paymentType: paymentType,
              #description: description,
              #customerName: customerName,
              #customerPhone: customerPhone,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deletePaymentReceipt(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePaymentReceipt, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
