// Mocks generated by Mockito 5.4.6 from annotations
// in picklemart/test/unit/orders/order_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:picklemart/features/cart/application/cart_controller.dart'
    as _i5;
import 'package:picklemart/features/orders/data/order_model.dart' as _i2;
import 'package:picklemart/features/orders/data/order_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrder_0 extends _i1.SmartFake implements _i2.Order {
  _FakeOrder_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i3.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Order> createOrder({
    String? orderNumber,
    required List<_i5.CartItem>? cartItems,
    required _i2.OrderAddress? deliveryAddress,
    required double? subtotal,
    required double? shipping,
    required double? tax,
    required double? total,
    String? notes,
    String? userId,
    _i2.OrderStatus? status,
    double? oldDue = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #orderNumber: orderNumber,
              #cartItems: cartItems,
              #deliveryAddress: deliveryAddress,
              #subtotal: subtotal,
              #shipping: shipping,
              #tax: tax,
              #total: total,
              #notes: notes,
              #userId: userId,
              #status: status,
              #oldDue: oldDue,
            }),
            returnValue: _i4.Future<_i2.Order>.value(
              _FakeOrder_0(
                this,
                Invocation.method(#createOrder, [], {
                  #orderNumber: orderNumber,
                  #cartItems: cartItems,
                  #deliveryAddress: deliveryAddress,
                  #subtotal: subtotal,
                  #shipping: shipping,
                  #tax: tax,
                  #total: total,
                  #notes: notes,
                  #userId: userId,
                  #status: status,
                  #oldDue: oldDue,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Order>);

  @override
  _i4.Future<_i2.Order?> getOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [orderId]),
            returnValue: _i4.Future<_i2.Order?>.value(),
          )
          as _i4.Future<_i2.Order?>);

  @override
  _i4.Future<List<_i2.Order>> getUserOrders({int? page = 1, int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, [], {#page: page, #limit: limit}),
            returnValue: _i4.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i4.Future<List<_i2.Order>>);

  @override
  _i4.Future<List<_i2.Order>> getAllOrders({
    int? page = 1,
    int? limit = 50,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllOrders, [], {
              #page: page,
              #limit: limit,
              #searchQuery: searchQuery,
            }),
            returnValue: _i4.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i4.Future<List<_i2.Order>>);

  @override
  _i4.Future<_i2.Order?> updateOrderStatus(
    String? orderId,
    _i2.OrderStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [orderId, status]),
            returnValue: _i4.Future<_i2.Order?>.value(),
          )
          as _i4.Future<_i2.Order?>);

  @override
  _i4.Future<_i2.Order?> updateOrderItems(
    String? orderId,
    List<_i2.OrderItem>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderItems, [orderId, items]),
            returnValue: _i4.Future<_i2.Order?>.value(),
          )
          as _i4.Future<_i2.Order?>);

  @override
  _i4.Future<_i2.Order?> updateOrderDeliveryAddress(
    String? orderId,
    _i2.OrderAddress? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderDeliveryAddress, [orderId, address]),
            returnValue: _i4.Future<_i2.Order?>.value(),
          )
          as _i4.Future<_i2.Order?>);

  @override
  _i4.Future<_i2.Order?> updateOrderDetails({
    required String? orderId,
    required _i2.OrderAddress? deliveryAddress,
    required double? shipping,
    double? oldDue = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderDetails, [], {
              #orderId: orderId,
              #deliveryAddress: deliveryAddress,
              #shipping: shipping,
              #oldDue: oldDue,
            }),
            returnValue: _i4.Future<_i2.Order?>.value(),
          )
          as _i4.Future<_i2.Order?>);

  @override
  _i4.Future<bool> deleteOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [orderId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getOrderMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getOrderMetrics, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
